# conf.py — Sphinx configuration for PyEvoc API documentation.
# Generated by build_pyevoc_sphinx_api_reference.ipynb.

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

project   = "PyEvoc"
author    = "Michelangelo Misuraca"
copyright = "2026, Michelangelo Misuraca"

try:
    import pyevoc
    release = getattr(pyevoc, "__version__", "0.2.1")
except Exception:
    release = "0.2.1"

# ── Extensions ────────────────────────────────────────────────────────────
extensions = [
    "sphinx.ext.autodoc",
    # sphinx.ext.autosummary intentionally removed: with autosummary_generate=True
    # it iterates pyevoc.__all__ (which includes "__version__"), crashing Sphinx 8.x.
    # With an explicit module list it expects .rst files at the source root, but
    # ours live in api_reference/ — producing 30 file-not-found warnings.
    # All RST stubs are written explicitly by this notebook; autosummary is not needed.
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "myst_parser",
]

# ── Autodoc ───────────────────────────────────────────────────────────────
autodoc_member_order      = "bysource"
autodoc_typehints         = "description"
autodoc_typehints_format  = "short"
autodoc_preserve_defaults = True
autodoc_class_signature   = "mixed"

# Mock optional heavy dependencies so import never fails during the build
autodoc_mock_imports = [
    "stanza", "fasttext", "fasttext_wheel",
    "lingua", "lingua_language_detector",
    "emoji", "plotly", "matplotlib", "kaleido",
    "networkx", "scipy", "sklearn",
    "openpyxl", "pyarrow", "adjustText", "bs4",
]

autodoc_default_options = {
    "members":          True,
    "undoc-members":    False,
    "show-inheritance": True,
    "member-order":     "bysource",
    "exclude-members":  "__weakref__,__dict__,__module__,__version__,__all__,__getattr__,__dir__",
}

# ── Napoleon (docstring styles) ───────────────────────────────────────────
napoleon_google_docstring        = True
napoleon_numpy_docstring         = True
napoleon_include_init_with_doc   = True
napoleon_include_private_with_doc  = False
napoleon_include_special_with_doc  = False

# ── Intersphinx ───────────────────────────────────────────────────────────
intersphinx_mapping = {
    "python":  ("https://docs.python.org/3", None),
    "pandas":  ("https://pandas.pydata.org/docs/", None),
    "numpy":   ("https://numpy.org/doc/stable/", None),
    "sklearn": ("https://scikit-learn.org/stable/", None),
    "scipy":   ("https://docs.scipy.org/doc/scipy/", None),
}

# ── Nitpick suppression ────────────────────────────────────────────────────
# Suppress unresolvable cross-references for types that live in mocked or
# internal namespaces. These are annotated correctly in the source; they
# simply do not appear under their internal paths in any intersphinx inventory.
nitpick_ignore_regex = [
    # pandas internal module paths (not exposed in the public inventory)
    (r"py:class", r"pandas\.core\..*"),
    (r"py:class", r"pandas\._libs\..*"),
    # sklearn internals
    (r"py:class", r"sklearn\..*"),
    # scipy internals
    (r"py:class", r"scipy\..*"),
    # mocked optional dependencies
    (r"py:class", r"plotly\..*"),
    (r"py:class", r"matplotlib\..*"),
    (r"py:class", r"networkx\..*"),
    (r"py:class", r"fasttext\..*"),
    (r"py:class", r"stanza\..*"),
    # unqualified :func: cross-refs inside plots.py docstrings
    (r"py:func",  r"compute_node_sizes"),
    (r"py:func",  r"get_aoe_threshold"),
]

# ── Templates & patterns ──────────────────────────────────────────────────
templates_path   = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# ── HTML theme — pydata-sphinx-theme ─────────────────────────────────────
html_theme       = "pydata_sphinx_theme"
html_title       = "PyEvoc API Reference"
html_short_title = "PyEvoc API"
html_static_path = ["_static"]
html_css_files   = ["pyevoc_api.css"]
html_favicon     = None

html_theme_options = {
    # Logo: pydata-sphinx-theme reads html_theme_options["logo"].
    # "image_light" / "image_dark" are paths relative to _static/.
    # "text" is shown as a fallback if the image fails to load.
    "logo": {
        "image_light": "pyevoc_logo.svg",
        "image_dark":  "pyevoc_logo.svg",
        "text":        "PyEvoc API",
        "alt_text":    "PyEvoc",
    },
    "show_toc_level":      2,
    "navigation_depth":    4,
    "collapse_navigation": False,
    "navbar_align":  "left",
    "navbar_start":  ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end":    ["theme-switcher", "navbar-icon-links"],
    "footer_start":  ["copyright"],
    "footer_center": [],
    "footer_end":    [],
    "icon_links": [
        {
            "name": "GitHub",
            "url":  "https://github.com/text-lab/pyevoc",
            "icon": "fa-brands fa-github",
        },
        {
            "name": "Zenodo",
            "url":  "https://doi.org/10.5281/zenodo.20545334",
            "icon": "fa-solid fa-book",
        },
    ],
    "pygments_light_style": "friendly",
    "pygments_dark_style":  "monokai",
}

html_context  = {"default_mode": "light"}
html_sidebars = {"**": ["sidebar-nav-bs", "page-toc"]}

source_suffix = {".rst": "restructuredtext", ".md": "markdown"}
todo_include_todos = False
